#!/bin/bash

# Generate Xcode Project Script for Beacon Attendance
# Run this script to generate the Xcode project file

echo "🚀 Generating Xcode project for Beacon Attendance..."

# Check if we're in the right directory
if [ ! -f "Package.swift" ]; then
    echo "❌ Error: Package.swift not found. Please run this script from the project root."
    exit 1
fi

# Clean any existing build artifacts
echo "🧹 Cleaning build artifacts..."
rm -rf .build
rm -rf .swiftpm

# Generate Xcode project using Swift Package Manager
echo "💡 Xcode projects are now generated by opening Package.swift directly in Xcode."
echo "    No explicit command is needed to 'generate' it."

# We will still run `swift package resolve` to ensure dependencies are fetched
echo "🔄 Resolving package dependencies..."
swift package resolve

# Check if generation was successful
if [ $? -eq 0 ]; then
    echo "✅ Package dependencies resolved successfully!"
    echo ""
    echo "📝 Next steps:"
    echo "1. Open the Package.swift file directly in Xcode (File > Open... then navigate to Package.swift)"
    echo "2. Xcode will automatically generate the project and fetch dependencies."
    echo "3. Select a development team in project settings."
    echo "4. Set the deployment target to iOS 14.0+."
    echo "5. Build and run on a physical device (iBeacon doesn't work on simulator)."
    echo ""
    echo "⚠️  Important:"
    echo "- Test on a real device (iBeacon requires physical hardware)"
    echo "- Grant 'Always' location permission when prompted"
    echo "- Enable Background App Refresh in Settings"
    echo "- Have a beacon with UUID: FDA50693-0000-0000-0000-290995101092"
else
    echo "❌ Failed to resolve package dependencies."
    echo "Please ensure you have Xcode and Swift tools installed"
    exit 1
fi
